Repository iodepo/odis-arch, pull requests merged in 2023-08, with the labels that each got.

#280 clarify vessels definition
  book/thematics/expinst/README.md
  book/thematics/vessels/README.md
  code/notebooks/Exploration/dashboard/dashboard.py
Labels: documentation

#182 126 [WOD] world ocean database connection
  book/thematics/dataset/graphs/wodCastDataset.json
Labels: pattern development, partners

#141 pattern development DataFeed template
  book/thematics/datafeed/DataFeed.json
Labels: pattern development

#308 initial ODISCat pattern sample
  book/thematics/expinst/graphs/odisCatOrganization-example.json
Labels: pattern development

#239 initial WMO example pattern
  book/thematics/dataset/graphs/wmoCoreExample.json
Labels: pattern development, partners

#236 Observation pattern draft
  book/thematics/Observation/graphs/Observation.json
  book/thematics/QuantitativeValue/graphs/QuantitativeValue.json
  workflows/output/2023-06-01T0011_sitemaps.csv
Labels: pattern development, partners

#158 First pass at future events
  book/thematics/events/graphs/futureEvent.json
Labels: pattern development

#147 OBON dataset sub-pattern
  book/thematics/dataset/graphs/obonDataset.json
Labels: pattern development, partners
